<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \ALevel\PrivateCache\Block\Account\Dashboard\BloodPoints $block */
?>
<div class="block block-dashboard-blood-points">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Blood Points Info')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Balance')) ?></span>
            </strong>
            <div class="box-content">
                <p><?= $block->escapeHtml($block->getPoints()) ?></p>
            </div>
    </div>
</div>
